### ISSUE TITLE
Not an issue: Haveged is a life saver on headless Raspis...

### ISSUE THREAD

**Issue by rin67630** [jirka-h/haveged#11]
Just to mention: many headless Raspberry Pi installations will not boot correctly since the current kernel is using mouse events to generate entropy. Not finding a mouse it will wait for minutes, frequently forever.
Haveged is a life saver!
The headless Raspberry Pi is now rebooting in seconds where it took minutes, or worse got stuck...

**Comment by kravietz** [comment]
@rin67630 For that purpose you might also consider [pollinate](http://manpages.ubuntu.com/manpages/trusty/man1/pollinate.1.html) whose purpose is precisely to seed PRNG on boot intended to use in machines with limited entropy sources.

**Comment by jirka-h** [comment]
Thank you for the positive feedback!
