### ISSUE TITLE
Signed sources

### ISSUE THREAD

**Issue by eworm-de** [jirka-h/haveged#2]
The origin website (http://www.issihosts.com/haveged/) has all source tarballs up to version 1.9.2, but latest one is missing a gpg signature. As development moved here - Any chance to have a download for latest version with signature? I'd be happy with a signed git tag in the repository as well.

**Comment by jirka-h** [comment]
Thanks for bringing it up! I have created a release with the signature here:

https://github.com/jirka-h/haveged/releases/tag/1.9.2

Please let me know if you need anything else.

**Comment by eworm-de** [comment]
I can not find the public key. Where to get it?

**Comment by jirka-h** [comment]
Please get my GPG key here:

$gpg --keyserver hkp://keys.gnupg.net --recv-keys 2E2F252B05CCA168

I'm still checking what is the best way to sign the releases. I have followed the steps described here:

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

I have also added my public GPG key to my Github account but I'm not sure if others can use it. 

Do you have some tips on how to distribute the GPG public key and sign the releases? 

Thanks!
Jirka

**Comment by eworm-de** [comment]
Looks like your key did not yet spread to all keyservers, that is why I did not find it.
IMHO everything looks fine now. Thanks a lot!

**Comment by eworm-de** [comment]
Can you please sign latest releases? Thanks!
