### ISSUE TITLE
Unresolved symbol error_exit in libhavege

### ISSUE THREAD

**Issue by jpalus** [jirka-h/haveged#20]
havegecmd.c uses error_exit function that is only defined in haveged.c and therefore it is not resolved in libhavege library. error_exit() is rather not suitable for a library so please either drop error_exit usage from havegecmd.c or move havegecmd.c from library to haveged daemon.

**Comment by jirka-h** [comment]
Fixed by 525a47d5a51b4d3137345dcb019f27fd04f4b704
