### ISSUE TITLE
service.fedora hardcodes sbin path

### ISSUE THREAD

**Issue by bazineta** [jirka-h/haveged#25]
This commit:

https://github.com/jirka-h/haveged/commit/1470a82a7f79110c79beea1ca5f2d3b0fd1a4668#diff-3fb7fcf3839c90e687c11965ea6abf98

Removed the `@SBIN_DIR@` variable from `service.fedora`, instead hardcoding /usr/sbin.

We're using Amazon Linux 2 systems, and the following:
```
	./configure --enable-init=service.fedora
	make
	sudo make install
```
Puts the installation into the `/usr/local` path, which is where we want it to go, but we're now having to change the service file after installation to point to `/usr/local/sbin`; that was automatic prior to that commit.

**Comment by jirka-h** [comment]
Thanks for the report! I have fixed it now. 

Commit 9d034d14c1847fdf029b56dcc4459cb1eb64979e
