### ISSUE TITLE
The project lacks LICENSE file

### ISSUE THREAD

**Issue by sxiii** [jirka-h/haveged#27]
Greetings. I don't see a LICENSE file in here. Probably worth adding? Thanks.

**Comment by nckx** [comment]
It's right there in the root directory: https://github.com/jirka-h/haveged/blob/master/COPYING … :confused:

**Comment by jirka-h** [comment]
Thanks for answering this one. 

See also 
https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project
