### ISSUE TITLE
Repeat the haveged  command will abort

### ISSUE THREAD

**Issue by zjxcliangyun** [jirka-h/haveged#29]
After the haveged service was started,  then repeat the haveged command :
   /usr/sbin/haveged -w 1024 -v 1 --Foreground
The command will abort.
The reason is that the "sys/entropy/haveged"socket is already used and can not create again,  so cmd_listen return -1.
But the program is not care about the error  ,then FD_SET will raise abort.

**Comment by jirka-h** [comment]
Fixed with 193b3320bbe98cbecd465c87a8116f6047c66fa6

**Comment by jirka-h** [comment]
Thanks for reporting it. We now disable command mode when there is another haveged instance already running.

**Comment by PrinterFranklin** [comment]
@jirka-h hi, why can't just error_exit when socket_fd < 0? With the community's patch, haveged will be waiting after input "/usr/sbin/haveged -w 1024 -v 1 --Foreground".
