### ISSUE TITLE
SPEC file missing patch information

### ISSUE THREAD

**Issue by daniejstriata** [jirka-h/haveged#31]
I want to build RPMs using the SPEC file but it is calling for a patch file that I can't find. I wanted to test, building a RPM for Centos 7. I am worried the that missing patch file is something important.

I looked at the source used for FC 32 and that SPEC file does not specify a patch file. I compiled v1.9.8 using the SPEC (I had to remove the tag mentioned on line 14) file supplied by FC 32 and that built a working version on Centos 7.8. The FC 32 version of the SPEC file does not include a Patch file.

```
# rpmbuild -ba haveged.spec 
error: Bad source: /root/rpmbuild/SOURCES/haveged-link.patch: No such file or directory

```

**Comment by jirka-h** [comment]
Hi,

FC 32 SPEC file is up-to-date. I have now updated contrib/build/fedora.spec here as well. 

commit 2a8748073db844d8de57823613642d59e99a875c

Thanks
Jirka
