### ISSUE TITLE
0002 RPATH error on build

### ISSUE THREAD

**Issue by aboese** [jirka-h/haveged#33]
Noticed an rpath error on build in rhel systems. Was trying to determine if there was something local, or that I could have been doing to cause this, but I'm not sure. I was maybe a minor version behind on some of the build tools required, but it didn't seem to make a difference with anything else. Anyone know?

0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
               nor relative filenames and can therefore be a SECURITY risk

**Comment by jirka-h** [comment]
Hello,

could you please be more specific? What version have you used and what command was causing the problems? 

I have just tried to compile the latest version on RHEL-8.2 and there were no issues:

wget https://github.com/jirka-h/haveged/archive/v1.9.9.tar.gz
tar xvf v1.9.9.tar.gz
cd haveged-1.9.9/
./configure 
make
make install

BTW, haveged can be also installed from EPEL repository:
https://centos.pkgs.org/8/epel-x86_64/haveged-1.9.8-1.el8.x86_64.rpm.html

Thanks
Jirka

**Comment by aboese** [comment]
Sorry for late response. Epel wasn’t permitted at environment. Error was probably self inflicted. Just thought I’d ask in case it wasn’t. Sorry for late reply. If I end up hit it again I’ll bounce you that info. Thanks for the assist.

-Alex

**Comment by jirka-h** [comment]
Thanks for the update.

I'm glad that it's working for you! :-)
