### ISSUE TITLE
service.fedora not pointing to binary

### ISSUE THREAD

**Issue by daniejstriata** [jirka-h/haveged#36]
Since version 1.9.8 the file service.fedora changed from 
`< ExecStart=/usr/sbin/haveged -w 1024 -v 1 --Foreground`
to
`> ExecStart=@SBIN_DIR@/haveged -w 1024 -v 1 --Foreground`

which does not get substituted.

I updated the file to point to the binary and built a new version from the included SPEC file, fedora.spec
Note that it has a date issue on line 119, "Tue 09 Jun 2020" should read "Tue Jun 09 2020"

**Comment by jirka-h** [comment]
Thanks for pointing it out! 

I have updated the spec file to replace @SBIN_DIR@ in haveged.service file with the actual path.

Commit: 4a0a00885aa41d8b080ac2c6bd7503bffd7b3e55
