### ISSUE TITLE
Outdated ChangeLog file in repo

### ISSUE THREAD

**Issue by BKPepe** [jirka-h/haveged#38]
In the repository, there is a file [ChangeLog](https://github.com/jirka-h/haveged/blob/master/ChangeLog), but it was not updated for 9 months and it shows there version changelog up to 1.9.8, there are no changes since then. 

I see some changes are mention in [Releases](https://github.com/jirka-h/haveged/releases), but not many.

**Comment by jirka-h** [comment]
Thanks for the notification! 

I have updated the ChangeLog file - see 02674ae4dc518a908f4e6248147fff588592fc53.

There was no significant change - just a couple of bug fixes, along with updates of the systemd service file.
