### ISSUE TITLE
segfault ... error 4 in libc-2.30.s

### ISSUE THREAD

**Issue by toralf** [jirka-h/haveged#46]
At my desktop and at my server (stable hardened Gentoo Linux) I do have this in my syslog:
```
Jul 22 17:29:15 t44 kernel: haveged[1390]: segfault at 7f2475f4bff8 ip 00007f2475da0c1c sp 00007fffa6b52260 error 4 in libc-2.30.so[7f2475d3b000+146000]
```
```
Jul 24 13:45:56 mr-fox kernel: haveged[1195]: segfault at 7fb67255eff8 ip 00007fb6723e6c1c sp 00007ffda75215f0 error 4 in libc-2.30.so (deleted)[7fb672381000+146000]
```
for sys-apps/haveged-1.9.8c when I stop that service.

**Comment by jirka-h** [comment]
Could you please try the latest version? You can download it from git and run it in the foreground. 

Thanks
Jirka

**Comment by toralf** [comment]
> Could you please try the latest version? You can download it from git and run it in the foreground.
> 
> Thanks
> Jirka

indeed -solved there
