### ISSUE TITLE
Job haveged.service/start deleted 

### ISSUE THREAD

**Issue by daniejstriata** [jirka-h/haveged#47]
Hi,

Not sure why this happens but every now and then I find that haveged is not longer running. When querying the service I get this output from systemd:
`Job haveged.service/start deleted to break ordering cycle starting with sysinit.target/start`
I'm running Centos 7 in these cases with the latest haveged from EPEL, 1.9.13.

To fix the issue I install the service again (although I'm not sure if this is a permanent fix yet):
`systemctl enable haveged --now`

**Comment by jirka-h** [comment]
Hi,

thanks for the report! I will try to reproduce it. 

I have found this post
https://unix.stackexchange.com/questions/193714/generic-methodology-to-debug-ordering-cycles-in-systemd

Could you try to run "systemd-analyze verify" as described in one of the answers on stackexchange? We need to find the cycle and break it. 

Thanks!
Jirka

**Comment by daniejstriata** [comment]
Hi,

I hope this will help. Is it possible that the service file did not get updated when I changed from using my own compiled haveged service to the one from EPEL?

```
Found ordering cycle on sysinit.target/start
Found dependency on haveged.service/start
Found dependency on basic.target/start
Found dependency on sockets.target/start
Found dependency on iscsiuio.socket/start
Found dependency on sysinit.target/start
Breaking ordering cycle by deleting job sockets.target/start
Job sockets.target/start deleted to break ordering cycle starting with sysinit.target/start
Found ordering cycle on sysinit.target/start
Found dependency on haveged.service/start
Found dependency on basic.target/start
Found dependency on sysinit.target/start
Unable to break cycle
Requested transaction contains an unfixable cyclic ordering dependency: Transaction order is cyclic. See system logs for details.

Error: org.freedesktop.systemd1.TransactionOrderIsCyclic: Transaction order is cyclic. See system logs for details.
Failed to create haveged.service/start: Resource deadlock avoided
```
[cycle.svg.zip](https://github.com/jirka-h/haveged/files/5062184/cycle.svg.zip)

**Comment by jirka-h** [comment]
Thanks for the data. The output of `systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After  haveged.service` is different on my system:

```
$ systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After  haveged.service
Requires=system.slice basic.target
Requisite=
Wants=
BindsTo=
PartOf=
Before=shutdown.target
After=system.slice basic.target systemd-journald.socket
```

I don't have "sysinit.target" in Before list. And I don't have any loops on my system, so I think this is root cause for the problem. 

> when I changed from using my own compiled haveged service to the one from EPEL?

This seems reasonable. Could you please run

```
rpm -Va haveged
```
to verify haveged installation? 

haveged.service on my system is:
$ more /usr/lib/systemd/system/haveged.service
```
[Unit]
Description=Entropy Daemon based on the HAVEGE algorithm
Documentation=man:haveged(8) http://www.issihosts.com/haveged/

[Service]
Type=simple
ExecStart=/usr/sbin/haveged -w 1024 -v 1 --Foreground
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

My haveged version:
```
$ rpm -qa | grep haveged
haveged-1.9.13-1.el7.x86_64
```

Please let me know if haveged.service is different on your system.

**Comment by daniejstriata** [comment]
Thanks. I'll refer back to this as I check my hosts with issues again but for now after enabling the service again they've not been stopped since.

One of the hosts I'm looking at matches your service file:
```
[Unit]
Description=Entropy Daemon based on the HAVEGE algorithm
Documentation=man:haveged(8) http://www.issihosts.com/haveged/


[Service]
Type=simple
ExecStart=/usr/sbin/haveged -w 1024 -v 1 --Foreground
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target

```
