### ISSUE TITLE
Wiki isn't really enabled?

### ISSUE THREAD

**Issue by justinclift** [jirka-h/haveged#5]
Just noticed that when someone clicks on the "Wiki" link for the repo, instead of going to a (probably empty) wiki it's just bouncing to the front Code page for the repo.

Do you reckon it's worth enabling the wiki, so people with an interest could potentially start adding useful docs? eg about the new stuff in 1.9.3 and 1.9.4. :smile:

**Comment by jirka-h** [comment]
Good point! I have enabled the WIKI. Feel free to add the content! :-)

**Comment by justinclift** [comment]
Just to point out, the wiki permissions still seem to be locked down.  eg no-one but project contributors can edit things.
