### ISSUE TITLE
ARM support status?

### ISSUE THREAD

**Issue by hramrach** [jirka-h/haveged#51]
The NEWS file says that it was tested on ARM and the README does not list ARM as supported.

What is the status there?

**Comment by jirka-h** [comment]
Ahoj Michale ;-) 

Yes, both aarch64 and armv7hl are supported. I have updated the README file. 

I have just tested it on aarch64 on RHEL-8.3.0:

```bash
dnf --enablerepo=haveged install haveged
systemctl stop haveged.service
timeout 20 pv /dev/random > /dev/null 
 113KiB 0:00:19 [6.38KiB/s] [  
systemctl start haveged.service
timeout 20 pv /dev/random > /dev/null 
30.3MiB 0:00:20 [1.50MiB/s] [ 
```

Thanks
Jirka
