### ISSUE TITLE
χ² test is flaky

### ISSUE THREAD

**Issue by nbraud** [jirka-h/haveged#55]
While working on the Debian package for `haveged`, with the latest version I ran into several intermittent test failures, both on my laptop and [in CI](https://salsa.debian.org/debian/haveged/-/jobs/1342470#L1359).

**Comment by jirka-h** [comment]
Hallo nicoo,

thanks for bringing this to my attention! I have double-checked the chi-square test and it works correctly. For fully random input data, it returns the p-value evenly distributed between 0-100%. I have verified it using this test 

```
for i in $(seq -w 1000); do
  ./entest -vf <(head -c 16M /dev/random) > "${i}_linux.log"
done
grep -Poh "Chi-Square: .*\(\K[0-9.]+" ./*linux.log > chi.txt
```

and examining the p-values using the R language. I got 24 failures out of 1000 runs which is in line with the test properties. See below. 

To reproduce my results try this:
```
cd ent
./examine_chi_square.sh
```
and check results in the `chi_square` directory:
```
examine_chi_square.summary => check the p-values of Kolmogorov-Smirnov and Chi-squared tests
Rplots.pdf => histogram of p-values from the Chi-Square test
```

The chi-square test will be marked as failed for a p-value less than 1% and more than 99%. It means that the test will fail with the probability of 2%, even with fully random input. 

The easiest way how to fix this is to repeat the test several times and check the number of failures. 

I'm proposing to repeat the test 10 times and mark it as failed if the number of fails is greater than 2. The probability of this happening with fully random input is .086%. This should make the test reliable again. 

https://www.wolframalpha.com/input/?i=probability+of+3+or+more+fails+in+10+trials+with+p%3D.98

See the file `ent/test.sh`. Please let me know what you think. 

Thanks
Jirka
