### ISSUE TITLE
does not compile under uClibc-ng

### ISSUE THREAD

**Issue by neheb** [jirka-h/haveged#56]
https://github.com/jirka-h/haveged/commit/26d35af198da01220ba4f7a1b987f17012476c00 broke compilation as sys/auxv.h is not available. Same as getauxval.

https://downloads.openwrt.org/releases/faillogs-19.07/arc_arc700/packages/haveged/compile.txt

**Comment by jirka-h** [comment]
Thanks for the report! I will merge your PRs.
