### ISSUE TITLE
Can't Build on Cygwin

### ISSUE THREAD

**Issue by jbaker6953** [jirka-h/haveged#6]
I was unable to build on cygwin until doing the following:

--- "src\\haveged.c"    2018-08-10 15:44:19.000000000 -0700
+++ "src\\haveged.c.new"        2018-09-04 06:29:12.694437600 -0700
@@ -26,9 +26,9 @@
 #include <signal.h>
 #include <fcntl.h>
 #include <sys/time.h>
+#include <unistd.h>

 #ifndef NO_DAEMON
-#include <unistd.h>
 #include <syslog.h>
 #include <sys/ioctl.h>
 #include <asm/types.h>

**Comment by jirka-h** [comment]
Thanks for the fix - I have merged to the master branch. 

commit 638e2f066ee91e70c7fff1dcf21831ef9b17d7af
