### ISSUE TITLE
Build failure with NO_COMMAND_MODE

### ISSUE THREAD

**Issue by nolange** [jirka-h/haveged#60]
v14 and the current master fail to build if `NO_COMMAND_MODE` is used.

The declaration for `extern int first_byte` will be missing when compiling `haveged.c`. Fix this by wrapping the line in an assignment:
```c
#ifndef NO_COMMAND_MODE
   first_byte = arg0[0];
#endif
```

**Comment by jirka-h** [comment]
Good catch! 

Fixed with 3427ae484cd8567145965af659c1fe17300c14b4
