### ISSUE TITLE
Segfault in obtaining data

### ISSUE THREAD

**Issue by smuellerDD** [jirka-h/haveged#62]
I have a reliable crasher when using haveged with the LRNG patch set.

The problem is in haveged in function run_daemon with the following lines:

```
 if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
         error_exit("Couldn't query entropy-level from kernel");
      /* get number of bytes needed to fill pool */
      nbytes = (poolSize  - current)/8;
```

This code assumes that the poolsize is strictly larger than the available
entropy /dev/random can process. This is true for the legacy /dev/random but
it is not true for the LRNG considering that it has additional entropy
sources.

Here is a gdb output:

(gdb) p poolSize
$10 = 1024
(gdb)
696           if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
(gdb)
699           nbytes = (poolSize  - current)/8;
(gdb) p current
$13 = 1093
(gdb) p nbytes
$14 = <optimized out>
(gdb) p (poolSize  - current)
$15 = 4294967227
(gdb) p (poolSize  - current)/8
$16 = 536870903
(gdb) n
700           if(nbytes<1)   continue;
(gdb) p nbytes
$17 = 536870903

This value is now used to pull the given amount of bytes from the kernel which naturally is a bit too much.

This debug log also shows that  (poolSize  - current)/8 will not turn negative as the division by 8 is done before any potential type cast.

**Comment by jirka-h** [comment]
Good catch! 

I have fixed it with 92362a0064395bdcf2b7c97cd7e716d9de9f277e - could you please test it? 

Thanks a lot
Jirka

**Comment by smuellerDD** [comment]
Confirmed, working.

Just a side note for which I am not sure whether I should report it in a separate report considering it is separate from the issue discussed here. I start the daemon with `-w 1024 -v 1 --Foreground` i.e. with the options Fedora 34 uses. This works to terminate, I hit twice CTRL+C followed CTRL+\ and I get the following:

```
# src/.libs/haveged -w 1024 -v 1 --Foreground
haveged: command socket is listening at fd 3
haveged starting up
haveged: ver: 1.9.15; arch: x86; vend: ; build: (gcc 11.2.1 ITV); collect: 128K
haveged: cpu: (VC); data: 64K (V); inst: 64K (V); idx: 39/40; sz: 53875/53875
haveged: tot tests(BA8): A:1/1 B:1/1 continuous tests(B):  last entropy estimate 8.00096
haveged: fills: 0, generated: 0
^C^C^\Verlassen (Speicherabzug geschrieben)
```

The last line means that haveged dumps core. Unfortunately with GDB I cannot debug it.

**Comment by jirka-h** [comment]
Thanks for the verification! 

I have tested it on F33, F34, and F35 beta, and I have not run into the issue with the coredump after terminating it with Ctrl+C. 

```
haveged -w 1024 -v 1 --Foreground
^Chaveged: Stopping due to signal 2
```

I wonder why you have hit Ctrl-C twice. In my case, haveged reacts to the first SIGINT signal immediately. 

CTRL+\  sends the SIGQUIT signal which causes the process to terminate and dump core - this explains the coredump and it is expected behavior. 

```
haveged -w 1024 -v 1 --Foreground
^\Quit (core dumped)
```

Could you please try to hit Ctrl-C only once and wait for few seconds if haveged terminates? In all my experiments, it has stopped immediately after pressing Ctrl-C - I had no chance to press Ctrl-C twice. 

Thanks!
Jirka

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 04:10 -0700 schrieb jirka-h:


After hitting Ctrl-C, nothing happens. Then I looked with top and saw that it
consumes 100% of one CPU core.

I am going to look for the issue. But if you have ideas...

Thanks
Stephan
> 
> Thanks!
> Jirka
> 
>

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 04:10 -0700 schrieb jirka-h:
> 
> 
> Could you please try to hit Ctrl-C only once and wait for few seconds if
> haveged terminates? In all my experiments, it has stopped immediately after
> pressing Ctrl-C - I had no chance to press Ctrl-C twice. 

It loops endlessly with the following:

pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[], sigsetsize=8})
= 1 (out [4], left {tv_sec=1, tv_nsec=999999239})
ioctl(4, RNDGETENTCNT, [1298])          = 0

I.e. the RNDGETENTCNT returns 1298 here. Note:

# cat /proc/sys/kernel/random/poolsize
1280

Thanks
Stephan
> 
> Thanks!
> Jirka
> 
>

**Comment by jirka-h** [comment]
Thanks for the logs! 

I'm still not able to reproduce it. Are you using a custom Linux kernel build? If so, could I get the rpms to test it? 

My test systems:
F34:
kernel 5.12.10-300.fc34.x86_64
haveged-1.9.15-1.fc34.x86_64.rpm https://koji.fedoraproject.org/koji/taskinfo?taskID=76514171
cat /proc/sys/kernel/random/poolsize
4096

F35:
kernel 5.14.0-0.rc6.46.fc35.x86_64
haveged-1.9.15-1.fc35.x86_64.rpm https://koji.fedoraproject.org/koji/taskinfo?taskID=76514163
cat /proc/sys/kernel/random/poolsize
4096


I have built a new version: haveged-1.9.15-1 for F34 (it contains the fix from yesterday). 
https://koji.fedoraproject.org/koji/taskinfo?taskID=76514035

Could you please try this version? It should be the same as your build from git, but I want to make sure we are using the same bits. 

Thanks a lot!
Jirka

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 05:40 -0700 schrieb jirka-h:
> Thanks for the logs! 
> 
> I'm still not able to reproduce it. Are you using a custom Linux kernel
> build? If so, could I get the rpms to test it? 

Note, I am running the haveged on a completely different /dev/random
implementation: https://github.com/smuellerDD/lrng

It is API and ABI compatible.

On unmodified kernels, it works as designed. This LRNG has the capability to
deliver more entropy than its "entropy pool" size as the entropy pool is
applied to two entropy sources. The LRNG however has four entropy sources
where the other two do not go through the entropy pool.

Thus, the pool size can be smaller than the entropy rate that is available.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 14:43 +0200 schrieb Stephan Mueller:
> Am Donnerstag, dem 30.09.2021 um 05:40 -0700 schrieb jirka-h:
> > Thanks for the logs! 
> > 
> > I'm still not able to reproduce it. Are you using a custom Linux kernel
> > build? If so, could I get the rpms to test it? 
> 
> Note, I am running the haveged on a completely different /dev/random
> implementation: https://github.com/smuellerDD/lrng
> 
> It is API and ABI compatible.
> 
> On unmodified kernels, it works as designed. This LRNG has the capability to
> deliver more entropy than its "entropy pool" size as the entropy pool is
> applied to two entropy sources. The LRNG however has four entropy sources
> where the other two do not go through the entropy pool.
> 
> Thus, the pool size can be smaller than the entropy rate that is available.

After fully updating to the git head, I still see the issue I reported:

696           if (conn_fd >= 0 && FD_ISSET(conn_fd, &read_fd))
(gdb)
699           if (!FD_ISSET(random_fd, &write_fd))
(gdb)
702           if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
(gdb)
705           nbytes = (poolSize  - current)/8;
(gdb)
706           if(nbytes<1)   continue;
(gdb) p poolSize
$1 = 1280
(gdb) p current
$2 = 1298
(gdb) p nbytes
$3 = 536870909

Ciao
Stephan
> 
> Ciao
> Stephan
>

**Comment by jirka-h** [comment]
Hallo Stephan,

OK, that was helpful! Now I understand what's happening. 

> After hitting Ctrl-C, nothing happens. Then I looked with top and saw that it consumes 100% of one CPU core.

This is wrong and we have to fix it. 

The key part is the pselect call. On unmodified kernels, this will wait (and eventually timeout) as long as available entropy (entropy_avail) is above the threshold (write_wakeup_threshold):
```
pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[], sigsetsize=8}) = 0 (Timeout)
```
On F34, right after boot:
```
cat /proc/sys/kernel/random/entropy_avail
3780
cat /proc/sys/kernel/random/write_wakeup_threshold  
3072
```

What are the values of `entropy_avail` and `write_wakeup_threshold` for your kernel? Please note that `haveged` will modify the `write_wakeup_threshold` value:

```
cat /proc/sys/kernel/random/write_wakeup_threshold  
3072
haveged -w 1024 -v 1 --Foreground
Ctrl-C
cat /proc/sys/kernel/random/write_wakeup_threshold                          
1024
```
On your kernel, this does not block, indicating that `entropy_avail < write_wakeup_threshold`
pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[], sigsetsize=8})
= 1 (out [4], left {tv_sec=1, tv_nsec=999999239})

Most likely `write_wakeup_threshold` is set incorrectly. Could you please post

```
cat /proc/sys/kernel/random/write_wakeup_threshold
```

immediately after booting the kernel and after running `haveged`? This way, we will find out where the root cause is. Most likely this is set incorrectly by `haveged`, but we need to get the values to be sure. 

Thanks a lot!
Jirka

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 07:06 -0700 schrieb jirka-h:
> Hallo Stephan,
> 
> OK, that was helpful! Now I understand what's happening. 
> 
> > After hitting Ctrl-C, nothing happens. Then I looked with top and saw that
> > it consumes 100% of one CPU core.
> 
> This is wrong and we have to fix it. 
> 
> The key part is the pselect call. On unmodified kernels, this will wait (and
> eventually timeout) as long as available entropy (entropy_avail) is above the
> threshold (write_wakeup_threshold):
> ```
> pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[], sigsetsize=8})
> = 0 (Timeout)
> ```
> On F34, right after boot:
> ```
> cat /proc/sys/kernel/random/entropy_avail
> 3780
> cat /proc/sys/kernel/random/write_wakeup_threshold  
> 3072
> ```
> 
> What are the values of `entropy_avail` and `write_wakeup_threshold` for your
> kernel? Please note that `haveged` will modify the `write_wakeup_threshold`
> value:
> 
> ```
> cat /proc/sys/kernel/random/write_wakeup_threshold  
> 3072

# cat /proc/sys/kernel/random/write_wakeup_threshold
32

This is the write wakeup appropriate for the LRNG.

> haveged -w 1024 -v 1 --Foreground
> Ctrl-C
> cat /proc/sys/kernel/random/write_wakeup_threshold                          
> 1024

It is not modified for me. After starting the haveged, it remains at 32.


> ```
> On your kernel, this does not block, indicating that `entropy_avail
> < write_wakeup_threshold`
> pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[],
> sigsetsize=8})
> = 1 (out [4], left {tv_sec=1, tv_nsec=999999239})
> 
> Most likely `write_wakeup_threshold` is set incorrectly. Could you please
> post
> 
> ```
> cat /proc/sys/kernel/random/write_wakeup_threshold
> ```
> 
> immediately after booting the kernel and after running `haveged`? This way,
> we will find out where the root cause is. Most likely this is set
> incorrectly by `haveged`, but we need to get the values to be sure. 
> 
> Thanks a lot!

Thank you.
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 16:17 +0200 schrieb Stephan Mueller:
> Am Donnerstag, dem 30.09.2021 um 07:06 -0700 schrieb jirka-h:
> > Hallo Stephan,
> > 
> > OK, that was helpful! Now I understand what's happening. 
> > 
> > > After hitting Ctrl-C, nothing happens. Then I looked with top and saw that
> > > it consumes 100% of one CPU core.
> > 
> > This is wrong and we have to fix it. 
> > 
> > The key part is the pselect call. On unmodified kernels, this will wait (and
> > eventually timeout) as long as available entropy (entropy_avail) is above
> > the
> > threshold (write_wakeup_threshold):
> > ```
> > pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[],
> > sigsetsize=8})
> > = 0 (Timeout)
> > ```
> > On F34, right after boot:
> > ```
> > cat /proc/sys/kernel/random/entropy_avail
> > 3780
> > cat /proc/sys/kernel/random/write_wakeup_threshold  
> > 3072
> > ```
> > 
> > What are the values of `entropy_avail` and `write_wakeup_threshold` for your
> > kernel? Please note that `haveged` will modify the `write_wakeup_threshold`
> > value:
> > 
> > ```
> > cat /proc/sys/kernel/random/write_wakeup_threshold  
> > 3072
> 
> # cat /proc/sys/kernel/random/write_wakeup_threshold
> 32

This is the crux with the current code, no documentation. The interface is
actually in bits.

After converting the LRNG to bits, I get

$ cat /proc/sys/kernel/random/write_wakeup_threshold
256

After I started haveged, I get

# cat /proc/sys/kernel/random/write_wakeup_threshold
480

The LRNG has the default of 256 and the max of 512 bits for those values.

But haveged still spins.

Thanks
Stephan

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 16:43 +0200 schrieb Stephan Mueller:
> Am Donnerstag, dem 30.09.2021 um 16:17 +0200 schrieb Stephan Mueller:
> > Am Donnerstag, dem 30.09.2021 um 07:06 -0700 schrieb jirka-h:
> > > Hallo Stephan,
> > > 
> > > OK, that was helpful! Now I understand what's happening. 
> > > 
> > > > After hitting Ctrl-C, nothing happens. Then I looked with top and saw
> > > > that
> > > > it consumes 100% of one CPU core.
> > > 
> > > This is wrong and we have to fix it. 
> > > 
> > > The key part is the pselect call. On unmodified kernels, this will wait
> > > (and
> > > eventually timeout) as long as available entropy (entropy_avail) is
> > > above
> > > the
> > > threshold (write_wakeup_threshold):
> > > ```
> > > pselect6(5, [3], [4], NULL, {tv_sec=2, tv_nsec=0}, {sigmask=[],
> > > sigsetsize=8})
> > > = 0 (Timeout)
> > > ```
> > > On F34, right after boot:
> > > ```
> > > cat /proc/sys/kernel/random/entropy_avail
> > > 3780
> > > cat /proc/sys/kernel/random/write_wakeup_threshold  
> > > 3072
> > > ```
> > > 
> > > What are the values of `entropy_avail` and `write_wakeup_threshold` for
> > > your
> > > kernel? Please note that `haveged` will modify
> > > the `write_wakeup_threshold`
> > > value:
> > > 
> > > ```
> > > cat /proc/sys/kernel/random/write_wakeup_threshold  
> > > 3072
> > 
> > # cat /proc/sys/kernel/random/write_wakeup_threshold
> > 32
> 
> This is the crux with the current code, no documentation. The interface is
> actually in bits.
> 
> After converting the LRNG to bits, I get
> 
> $ cat /proc/sys/kernel/random/write_wakeup_threshold
> 256
> 
> After I started haveged, I get
> 
> # cat /proc/sys/kernel/random/write_wakeup_threshold
> 480
> 
> The LRNG has the default of 256 and the max of 512 bits for those values.
> 
> But haveged still spins.

Side note: the write_wakeup_threshold may change by the kernel for the LRNG
for one particular circumstance. Would that be a problem? I would not assume
that considering that other users may update that value. Note, the spinning
happens with or without the write_wakeup_threshold being updated underneath
haveged.

Ciao
Stephan

**Comment by jirka-h** [comment]
Hallo Stephan,

I'm glad that we are making the progress! 

Clearly `entropy_avail` (1298) > `write_wakeup_threshold` (480). In this situation, `pselect` should block, indicating that `/dev/random` is not ready to accept new entropy.

I'm puzzled why it does not block. Could you please check the kernel code how it handles `write_wakeup_threshold`? We have to make `pselect` to block for write in this situation to fix the problem. Without it, it will always spin consuming 100% of the CPU. The ugly workaround is to add an artificial sleep there, but it's a wrong approach:

Ugly WA:
```
 if(nbytes<1) {
  sleep(1);
  continue;
}
```

> Side note: the write_wakeup_threshold may change by the kernel for the LRNG
> for one particular circumstance. Would that be a problem?

No, I don't think it's a problem. We just need to make sure that `pselect` will block for `/dev/random` for write operation when `entropy_avail` > `write_wakeup_threshold`.

I have now crippled haveged code trying to reproduce the behavior that you are seeing. I have removed `pselect` from the code. Now Ctrl-C does not stop `haveged` -  haveged is designed to be interrupted only at pselect (it's a safe point to stop the daemon. In other parts of code, SIGINT is ignored.):

```
man pselect
The pselect() system call allows an application to safely wait until either a file descriptor becomes ready or until a signal is caught.
```
With your kernel, `pselect` never waits so Ctrl-C does not work.

I have also checked the latest gdb data you have posted and I'm puzzled while nbytes overflows instead of being a negative value. It seems the binary you have tested does not include the fix. I have artificially increased the entropy level by 1024:
```
current += 1024;
```

to model your scenario and I'm getting nbytes to be negative value as expected:
```
(gdb) p current
$2 = 4948
(gdb) p poolSize
$3 = 4096
(gdb) p nbytes
$5 = -106
```

Please note that all variables are now (signed) integers:
```
(gdb) ptype nbytes
type = int
(gdb) ptype poolSize
type = int
(gdb) ptype current
type = int
```

Could you please check the types of the variables for {nbytes, poolSize, current} in your gdb session? 

SUMMARY: I believe that if we can fix `pselect` to block for `/dev/random` for write operation when `entropy_avail` > `write_wakeup_threshold`, we will solve all problems.

Please let me know your opinion on this. 

Viele Grüße!
Jirka

**Comment by jirka-h** [comment]
The full WA around broken `pselect`:

```
      if(nbytes<1)   {
#if  NUMBER_CORES>1
   pthread_sigmask(SIG_UNBLOCK, &mask, NULL);
#else
   sigprocmask(SIG_UNBLOCK, &mask, NULL);
#endif
        sleep(1);
        #if  NUMBER_CORES>1
   pthread_sigmask(SIG_BLOCK, &mask, &omask);
#else
   sigprocmask(SIG_BLOCK, &mask, &omask);
#endif
        continue;
      }
```

It works - haveged can now be stoped by Ctrl-C and it does not utilize CPU when entropy is not needed.

However, I really hope we can fix `pselect`. I assume that other userspace utilities will have similar problems as long as `pselect` does not block for `/dev/random`.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 09:16 -0700 schrieb jirka-h:
> Hallo Stephan,

Hi Jirka,
> 
> I'm glad that we are making the progress! 

:-)

I think I found the issue. The LRNG code expected that user space inserts
something if it is woken up. I have now changed it such that no such
expectation is made.

With that, the haveged works now as intended.

Ciao
Stephan

**Comment by jirka-h** [comment]
Wunderbar! 

I'm really glad that it's solved and we don't need the WA with the sleep. 

Alles Gute!
Jirka

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 30.09.2021 um 13:23 -0700 schrieb jirka-h:
> Wunderbar! 

:-)
> 
> I'm really glad that it's solved and we don't need the WA with the sleep. 

Yes, that would have been bad indeed.

Shall I close the bug or do you want to keep it open for your development?
> 
> Alles Gute!

Thank you for also helping me flush out my issues! Take care
Stephan

> Jirka
>

**Comment by jirka-h** [comment]
> Shall I close the bug or do you want to keep it open for your development?

Oh, it's already closed (smuellerDD closed this 17 hours ago). As I understand it, no change is needed on the haveged side, so we can keep it this way. If you run into any issues, please let me know. 

> Thank you for also helping me flush out my issues! 

Excellent! I'm happy that it was fruitful for both of us. I'm always open to discussions like this!

Take care
Jirka
