### ISSUE TITLE
haveged --version

### ISSUE THREAD

**Issue by Dmole** [jirka-h/haveged#67]
If haveged had a version option bug reports could be more informative.

    haveged -h

    Usage: haveged [options]

    Collect entropy and feed into random pool or write to file.
      Options:
     --buffer    , -b [] Buffer size [KW], default: 128
     --data      , -d [] Data cache size [KB], with fallback to: 16
     --inst      , -i [] Instruction cache size [KB], with fallback to: 16
     --file      , -f [] Sample output file,  default: 'sample', '-' for stdout
     --Foreground, -F    Run daemon in foreground
     --run       , -r [] 0=daemon, 1=config info, >1=<r>KB sample
     --number    , -n [] Output size in [k|m|g|t] bytes, 0 = unlimited to stdout
     --onlinetest, -o [] [t<x>][c<x>] x=[a[n][w]][b[w]] 't'ot, 'c'ontinuous, default: ta8b
     --pidfile   , -p [] daemon pidfile, default: /var/run/haveged.pid
     --verbose   , -v [] Verbose mask 0=none,1=summary,2=retries,4=timing,8=loop,16=code,32=test
     --write     , -w [] Set write_wakeup_threshold [bits]
     --help      , -h    This help

is not listing the version, but maybe it's in there:

    strings "$(which haveged)" | grep -P "\d\.\d\."
    1.9.1

**Comment by jirka-h** [comment]
Hi,

there is actually `--version` available [1]

I have noticed it's missing in the man page. I have added it there:
commit 00fd6e5e6c47d7732efcdc317d4f4aae2121c2cf

It seems you are 4 years old version. Please consider upgrading to a recent version. The latest stable version is v1.9.17.

Thanks
Jirka

[1]
```
haveged --version
haveged 1.9.17

Copyright (C) 2018-2022 Jirka Hladky <hladky.jiri@gmail.com>
Copyright (C) 2009-2014 Gary Wuertz <gary@issiweb.com>
Copyright (C) 2011-2012 BenEleventh Consulting <manolson@beneleventh.com>

License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Dmole** [comment]
lsb_release -d
    Description:	Ubuntu 18.04.6 LTS

Thanks I'll upgrade next month when Ubuntu 22.04 is out.
