### ISSUE TITLE
how to use "haveged -c "?

### ISSUE THREAD

**Issue by BornThisWay** [jirka-h/haveged#75]
```
[root@localhost haveged_lcov]# haveged -c "root=./tmp"
haveged: can't restart ./haveged: No such file or directory
```
or
```
[root@localhost haveged_lcov]# haveged -c "root=./tmp"
haveged: can't restart ./haveged: Permission denied
```

**Comment by jirka-h** [comment]
Hi,

the command mode currently only supports chroot system call. See

https://github.com/jirka-h/haveged/blob/1c5eb6b62a5eb111bd60715a136983f8e9df9ba5/contrib/SUSE/haveged-switch-root.service

for an example of usage. 

This is relevant info from manpage:

       -c cmd, --command=cmd
              Switch  to  command  mode  and send a command to an already running haveged process or daemon.  Currently the only known commands are close to close the current communication socket of the running haveged process as
              well as root=<new_root> where <new_root> is a place holder for the path of the real new root directory which should provide a haveged installation. The haveged process or daemon will perform a chroot(2) system  call
              followed by a execv(3) to become rebased within the new root directory.

I hope this helps. 
Jirka
