### ISSUE TITLE
haveged test suite passes even if only `1`s are produced?

### ISSUE THREAD

**Issue by adrelanos** [jirka-h/haveged#81]
Quote https://jakob.engbloms.se/archives/1374

> So I tried to remove all variations from the HAVEGE program. I replaced the “HARDTICKS” macro in HAVEGE with the constant 0 (zero) rather than reading the time stamp counter of the processor. This immediately failed the randomness test.
>
> However, when I used the constant 1 (one) instead, the ent test passed. And even nist almost passed with only a single missed test out of the 426 tests executed.

**Comment by ArrayBolt3** [comment]
To further verify, I modified one of the files such that it should make haveged only ever output 1:

```c
@@ -253,7 +253,8 @@ int havege_rng(            /* RETURN: number words read     */
    H_UINT i;
 
    for(i=0;i<sz;i++)
-      buffer[i] = havege_ndread((H_COLLECT *)h->collector);
+      buffer[i] = 1; // YIKES! Don't ever let this into production, this is for testing purposes only.
+      //buffer[i] = havege_ndread((H_COLLECT *)h->collector);
    h->error = ((H_COLLECT *)h->collector)->havege_err;
 #endif
    return h->error==(H_UINT)H_NOERR? (int) sz : -1;
```

As expected, this flunked all of the RNG tests, including ent and nist tests.

**Comment by adrelanos** [comment]
Great, so this issue does not exist. Thank you!
